spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: spr.shop22@gmail.com
    password: qksgtegnzfqzlrnf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  error:
    include-message: always
